
version: "3.8"
services:
  api:
    container_name: api
    restart: "always"
    build: .
    ports:
      - "3000:3000"
    image: jv/api:vB1.0.0
    user: "node"
    hostname: node
    links:
      - mongodb
    volumes:
      - .:/usr/src/api
    networks:
      - jv_backend_default
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    restart: "always"
    logging:
      driver: none
    networks:
      - jv_backend_default
    volumes:
      - $HOME/mongodb:/data/db
networks:
  jv_backend_default:
    external: true