
version: "3.8"
services:
  api:
    build:
      context: $PWD
      dockerfile: $PWD/Dockerfile
    image: jv/api:vB1.0.0
    container_name: api
    user: "node"
    hostname: node
    ports:
      - "3000:3000"
    restart: "always"
    links:
      - mongodb
    volumes:
    - $HOME/logs:/logs
    - $PWD/permission.json:/api/permission.json
    networks:
      - jv_backend_default
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    restart: "always"
    networks:
      - jv_backend_default
    volumes:
      - $HOME/mongodb:/data/db
networks:
  adbox_backend_default:
    external: true